apiVersion: v1
kind: Service
metadata:
  name: port-export-grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    name: http
  selector:
    app: kube-prometheus-stack-grafana

# Run using: kubectl apply -f monitoring/grafana-export-service.yaml
