---
- hosts: all
  vars_files:
    - ../env_variables
  tasks:
    - name: Add Kubernetes Signing Key
      shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add
      become: yes

    - name: Adding Kubernetes APT repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/kubernetes-focal main
        state: present
        update_cache: yes
        filename: kubernetes
        validate_certs: yes
      become: yes

    - name: Installing required packages
      apt:
        name: "{{ packages }}"
        state: present
      become: yes

    - name: Starting and Enabling the required services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items: "{{ services }}"
      become: yes

    - name: Allow Network Ports in UFW
      ufw:
        rule: allow
        port: "{{ item }}"
        state: enabled
      with_items: "{{ ports }}"
      become: yes

    - name: Enabling Bridge Firewall Rule
      become: yes
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
      notify: Reload sysctl