---
# This Ansible playbook is used to setup Prometheus stack on a GCP Kubernetes cluster.
- name: Setup Prometheus stack on GCP Kubernetes cluster
  hosts: firstMaster
  tasks:
    # This task creates a namespace named 'monitoring' in the Kubernetes cluster.
    - name: Create monitoring namespace
      shell: kubectl create namespace monitoring

    # This task downloads the Helm installation script.
    - name: Download Helm script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0755'

    # This task runs the Helm installation script.
    - name: Run Helm script
      shell: /tmp/get-helm-3

    # This task adds the Prometheus Helm chart repository.
    - name: Add Prometheus Helm chart repository
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    # This task updates the Helm chart repositories.
    - name: Update Helm chart repositories
      shell: helm repo update

    # This task installs the Prometheus stack using Helm in the 'monitoring' namespace.
    - name: Install Prometheus stack using Helm
      shell: helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring

    # This task waits for all pods in the 'monitoring' namespace to be running.
    - name: wait for All pods to be running
      shell: kubectl get pods -n monitoring --field-selector=status.phase!=Running
      register: prometheus_service_check
      until: prometheus_service_check.stdout == ""
      retries: 10
      delay: 10

    # This task patches the Grafana service to change its type to NodePort.
    - name: Patch Grafana service to NodePort
      shell: |
        kubectl patch svc kube-prometheus-stack-grafana -n monitoring -p '{"spec": {"type": "NodePort"}}'

    # This task gets the NodePort assigned to the Grafana service.
    - name: Get the NodePort assigned to Grafana
      shell: kubectl get svc kube-prometheus-stack-grafana -n monitoring -o jsonpath='{.spec.ports[?(@.port==80)].nodePort}'
      register: grafana_nodeport

    # This task saves the NodePort assigned to the Grafana service to a file.
    - name: Save Grafana NodePort to a file
      delegate_to: localhost
      lineinfile:
        path: ./nodeports
        line: "{{ grafana_nodeport.stdout }}"
        create: yes