---
- name: Setup Prometheus stack on GCP Kubernetes cluster
  hosts: firstMaster
  tasks:
    - name: Create monitoring namespace
      shell: kubectl create namespace monitoring

    - name: Download Helm script
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        dest: /tmp/get-helm-3
        mode: '0755'

    - name: Run Helm script
      shell: /tmp/get-helm-3

    - name: Add Prometheus Helm chart repository
      shell: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

    - name: Update Helm chart repositories
      shell: helm repo update

    - name: Install Prometheus stack using Helm
      shell: helm install kube-prometheus-stack prometheus-community/kube-prometheus-stack --namespace monitoring

    - name: wait for All pods to be running
      shell: kubectl get pods -n monitoring --field-selector=status.phase!=Running
      register: prometheus_service_check
      until: prometheus_service_check.stdout == ""
      retries: 10
      delay: 10

    - name: Patch Grafana service to NodePort
      shell: |
        kubectl patch svc kube-prometheus-stack-grafana -n monitoring -p '{"spec": {"type": "NodePort"}}'

    - name: Get the NodePort assigned to Grafana
      shell: kubectl get svc kube-prometheus-stack-grafana -n monitoring -o jsonpath='{.spec.ports[?(@.port==80)].nodePort}'
      register: grafana_nodeport

    - name: Save Grafana NodePort to a file
      delegate_to: localhost
      lineinfile:
        path: ./nodeports
        line: "{{ grafana_nodeport.stdout }}"
        create: yes